### ISSUE TITLE
Contract

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#1]
We need to write a contract to begin this project.

**Comment by NathanWalker** [comment]
@tjvantoll and others are creating the contract.

**Comment by tjvantoll** [comment]
Ping @valentinstoychev. Can you provide details here when you have them?

**Comment by valentinstoychev** [comment]
I'm working with Maria and finalizing it.

**Comment by NathanWalker** [comment]
@valentinstoychev thank you for update. No rush, but when you do have it, Instead of emailing to everyone, if you don't mind just uploading here would be great: http://www.infowrap.com/2269/files
If that link ^ 404's for you, may need to join the private group here:
http://www.infowrap.com/groups/188?member=9233bc46-73d8-4d47-9bd0-7741469e8ca5

That will help ensure the contract doesn't get lost in some of our littered inboxes!
Thanks!

**Comment by valentinstoychev** [comment]
@NathanWalker I have the agreement ready, but it seems like the above reg link has expired.

**Comment by valentinstoychev** [comment]
I can probably sent it in slack?

**Comment by NathanWalker** [comment]
@valentinstoychev here's s renewed link:
https://infowrap.com/groups/188?member=05e9ecb8-6cb1-4a95-b750-e07afe54bd49
These will always auto expire in 3 days for security reasons.
Thanks, looking fwd to reviewing it soon.

**Comment by valentinstoychev** [comment]
Hey @NathanWalker - I sent it to your gmail address. I couldn't figure out how to use the system.

**Comment by NathanWalker** [comment]
@valentinstoychev for future ref, the Infowrap member invites I have been sending you expire within 3 days of the time I send them to you. If you wait longer than 3 days to click the link, they will not work. Here is a renewed link which will again expire in 3 days:
http://www.infowrap.com/groups/188?member=dc9f315d-738d-488c-a9f0-fa65501a3d5f

Further, you cannot be inside an Incognito browser window or have private browsing on as localStorage and IndexedDB must be fully accessible by Infowrap upon accepting the link.
