### ISSUE TITLE
How to style to Segmentbar 

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/theme#110]
How do I style the segmentbar? I have been looking around to find possible css examples but all I am seeing is beautiful screenshots but no code. Can anyone point me in the right direction? I would like to style the buttons selected color,  width,  etc.

**Comment by NathanWalker** [comment]
Hi @leocrawf, the SegementedBar is the 1 UI component which has been under development with more css support. Over the past 2 months, there's been a mixture of XML attributes you could mix with some limited css support for that component.

Starting with {N} 2.4.0, you can now use `selectedBackgroundColor` on the XML element itself in addition to defining via CSS:
```
.segmented-bar {
  selected-background-color: pink;
}
```
