### ISSUE TITLE
Creating theme aware class definitions

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#111]
Reviewing the default class definitions for light and dark themes.

If I wanted to create a horizontal separator line - I see there's a hr-light and hr-dark definitions. But wouldn't it also be useful if there was a class definition that would be aware of the current active theme.

i.e. if light theme is active - a class definition for HR would be a dark color and if dark theme is active the HR would draw a light color.

So in the user client app - they would just write  class="HR" 

Makes sense or did I miss something.

Thanks.

**Comment by NathanWalker** [comment]
Hi @erjdriver, hope you're enjoying using the theme.

The `hr-light` and `hr-dark` classes are not related to light/dark skins. They are actually 2 alternate divider classes. One is light is color, the other is darker.

We could however make `hr-dark` *smart* and detect if the user is using the `core.dark` skin, and could invert the color, whatcha' think?

**Comment by erjdriver** [comment]
I haven't looked at the theme file in great detail - but I'd like to make a suggestion.

By and large the purpose of such theme files should be for the user to select a theme (light or dark) and all ui still looks good and legible - i.e. color should be completely abstracted out.

So in my case - user just wants a divider line - doesn't care about the theme.

Case in point is - there's the `text-primary` definition. So I think you guys get the idea.


On a related note, sometimes there's also a need to know a certain color in javascript - for example the active theme's `text-primary` color. Is that possible?

Maybe the plug-in can include a js class definition that has stub methods to return a bunch of class definition colors.
