### ISSUE TITLE
No way to Justify Text

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/theme#114]
Is there a way to justify text? I am not seeing anything is the docs.

**Comment by NickIliev** [comment]
Hi @leocrawf 

At this very moment `text-justify` and `text-align:justify` are not supported CSS properties (for text-align you can set left, right and center) in NativeScript so this is the reason you are not seeing it in nativescript-theme as well.

**Comment by Cayan** [comment]
Is there any estimation for this feature?

**Comment by johnnyzen** [comment]
second this request please

**Comment by venkateshsj** [comment]
Would love to see this small but important feature!

**Comment by leocrawf** [comment]
When I played around with android java,  a seasoned developer told me it was not possible to justify text at that time. I am not sure if that is the case. Maybe that is why it is not implemented as yet.
