### ISSUE TITLE
scss - rules in platforms folder not being applied

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#116]
Using the latest version with scss installed also.

I'm using RadSideDrawer with core-dark theme and noticed that the list-item text was too dark - difficult to view it with the dark background.

This is my main.scss

`@import 'nativescript-theme-core/scss/dark';
$item-color-android : red;
@import 'nativescript-theme-core/scss/index';`

I see a file in node_modules\nativescript-theme-core\scss\platforms\_side-drawer.android.scss with the definition of 

`.sidedrawer-list-item-icon, .sidedrawer-list-item{
  color:$item-color-android;
}`

It seems like this rule was not being used - that's why I overrode it in my code to red - still not happening.

When is this file under platforms folder loaded...I didn't see any reference to it.

**Comment by NathanWalker** [comment]
Updated theme docs will be available by the end of the week which will provide more direction in regards to this. I'll report back when they go live.

**Comment by erjdriver** [comment]
Thanks - I'll wait for it...

But can you tell me why text color wasn't being applied to `sidedrawer-list-item` even though it's set in /platforms/ folder and I was also explicitly setting it in my .scss file.

**Comment by erjdriver** [comment]
Ok I see the problem.

After reviewing the docs - now the platform files loads and things looking much better.

**Comment by NathanWalker** [comment]
Excellent good to hear 👍 
Thanks for reporting anything you find!
