### ISSUE TITLE
Difference between theme and and theme-core

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#118]
Dumb question alert - what's the difference between nativescript-theme and nativescript-theme-core.

Which one should be used and also how installed - using tns or npm.

I've got the latter installed and seems to be working.

One feature I would like is to allow users to change themes.

Thanks.

**Comment by NathanWalker** [comment]
Hi @erjdriver there is no `nativescript-theme`, I assume you are referring to [nativescript-themes](https://github.com/nathanaela/nativescript-themes) - plural...which is a plugin to live switch css stylesheets in your app. The demo app in the `nativescript-theme-core` uses it for instance. The reason around the naming will be clarified in an upcoming blog post 👍 
<img width="453" alt="screen shot 2016-11-27 at 1 54 18 pm" src="https://cloud.githubusercontent.com/assets/457187/20652178/18c92c2e-b4a9-11e6-8319-093f6dbbb5f7.png">

**Comment by NathanWalker** [comment]
To understand how to change themes on the fly for your users, refer to that plugin: https://github.com/nathanaela/nativescript-themes
You can also see example usage in the demo app here:
https://github.com/NativeScript/theme/blob/master/app/pages/themes.ts#L26
Using that plugin here:
https://github.com/NativeScript/theme/blob/master/app/pages/themes.ts#L6
