### ISSUE TITLE
Have installed nativescript-theme-core

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#120]
I've installed nativescript-theme-core and also sass and have gotten my app to work - works with a single theme at a time. I can change the sass file and recompile to work with another theme.

What do I need to do so that user can change the themes at run-time?

I saw some code in the demo app - but am confused as to how to incorporate that code within my app - I already have nativescript-theme-core installed.

Thanks.

**Comment by NickIliev** [comment]
Hey @erjdriver 

There is a [very nice blog post on that matter](https://www.thepolyglotdeveloper.com/2016/11/changing-a-nativescript-css-skin-at-runtime/) by the Polyglot developer

**Comment by NathanWalker** [comment]
@erjdriver there is also a `free` video on how this can be achieved here:
https://egghead.io/lessons/angular-2-use-the-nativescript-themes-plugin-to-switch-app-themes-on-the-fly

**Comment by erjdriver** [comment]
Thanks.

Looks like that swaps CSS files.

My app uses SCSS files - I would think the translation from SCSS to CSS would have to happen at runtime.

**Comment by erjdriver** [comment]
I think that video explains quite a bit.

Thank you.

**Comment by NathanWalker** [comment]
@erjdriver Lemme know if you have any additional specific requests of how-to videos you would like covered and I'll add to a todo-list to publish to egghead soon. Cheers.

**Comment by erjdriver** [comment]
Thank you so much for the video - there was a big disconnect in my understanding especially with the .scss files etc.

The video explained it all - a video is truly worth a 1000 words.

Thanks.

**Comment by NathanWalker** [comment]
I'm a big video learner as well, agreed, glad it helped!

.scss files are ignored in final app.

Assuming default.css exists, it should.
