### ISSUE TITLE
Unable to use the theme-core css

### ISSUE THREAD

**Issue by realtebo** [NativeScript/theme#122]
I just created a fresh new app, is ALL unchanged from the template

I added to app.component.ts @Component this

    styleUrls : [ 'app.css' ],

And now I cannot run the app

```
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: File /data/data/org.nativescript.mynsapp/files/app/nativescript-theme-core/css/core.light.css does not exist. Resolved from: nativescript-theme-core/css/core.light.css.
```

My app.css file is the default: 

```
/*
In NativeScript, the app.css file is where you place CSS rules that
you would like to apply to your entire application. Check out
http://docs.nativescript.org/ui/styling for a full list of the CSS
selectors and properties you can use to style UI components.

/*
For example, the following CSS rule changes the font size of all UI
components that have the btn class name.
*/
.btn {
    font-size: 18;
}

/*
In many cases you may want to use the NativeScript core theme instead
of writing your own CSS rules. For a full list of class names in the theme
refer to http://docs.nativescript.org/ui/theme.
*/
@import 'nativescript-theme-core/css/core.light.css';
```

And, of course, I've already executed 

    npm install
    tns platform add android
    tns run android

What's the right way to use provided css files?
I don't see any differences from what stated here: http://docs.nativescript.org/ui/theme

**Comment by NathanWalker** [comment]
Run this: 'tns --version'
Please let us know what version that says.

**Comment by realtebo** [comment]
I restart from scratch

```
node -v
v7.2.1

npm -v
3.10.10

tns info
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-core-modules │ 2.4.2           │ 2.4.2          │ Up to date    │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date    │
│ tns-ios          │                 │ 2.4.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

I create a blank project
```
tns create theme-test-app --ng
cd theme-test-app
tns platform add android
```

First execution, _without any modification_, works and show me this

![image](https://cloud.githubusercontent.com/assets/1268699/21217248/8859930c-c2ab-11e6-9c42-14082e1e6071.png)

Next, to try a different theme, I do these changes:

1.  Into `app.css`:  I change 
    `@import 'nativescript-theme-core/css/core.light.css';` 
into 
    `@import 'nativescript-theme-core/css/purple.css';`

2. Into `app.component.ts`, in the `@Component` decorator config, I add 
    `styleUrls: [ 'app.css' ],`

Then `tns run android` again

![image](https://cloud.githubusercontent.com/assets/1268699/21217504/cd5316da-c2ac-11e6-99ae-cbbd5c3a0059.png)

I tried to _remove the css explicit declaration from the component_ and the re-run

    // styleUrls: [ 'app.css' ],

The app runs, but the purple theme is not applied

![image](https://cloud.githubusercontent.com/assets/1268699/21217589/3906a1bc-c2ad-11e6-89ec-bd0b1c8bcc3e.png)

What am I doing wrong?

**Comment by NickIliev** [comment]
Hey @realtebo I can confirm that indeed the purple theme is not loading.
Keep in mind that you do not have to provide   ` styleUrls: [ 'app.css' ]` in your app.component.ts as the styles from app.css will be globally applied by default. In fact adding the styleUrls is causing your application to throw with your error.

However, I can confirm that the purple theme is **not** applying as expected. Neither do some of the other pre-defined color themes. I have tested all of them and here is how the themes are rendered right now

aqua
![theme-aqua](https://cloud.githubusercontent.com/assets/18008302/21227751/e2cd566a-c2e3-11e6-9697-13caf60ed48e.png)

blue
![theme-blue](https://cloud.githubusercontent.com/assets/18008302/21227749/e2cb6b0c-c2e3-11e6-9b9d-191b2fd6b41b.png)
brown
![theme-brown](https://cloud.githubusercontent.com/assets/18008302/21227754/e2da3e7a-c2e3-11e6-957c-5151f57a7a07.png)

forest
![theme-forest](https://cloud.githubusercontent.com/assets/18008302/21227750/e2cd4080-c2e3-11e6-89da-77562bcddebb.png)

grey
![theme-grey](https://cloud.githubusercontent.com/assets/18008302/21227752/e2d19b30-c2e3-11e6-8b3c-1bf9dc9c057a.png)

lemon
![theme-lemon](https://cloud.githubusercontent.com/assets/18008302/21227753/e2d4d28c-c2e3-11e6-8881-f2987481b402.png)

lime
![theme-lime](https://cloud.githubusercontent.com/assets/18008302/21227755/e2e4b95e-c2e3-11e6-9cf6-c91105111068.png)

orange
![theme-orange](https://cloud.githubusercontent.com/assets/18008302/21227756/e2e69fd0-c2e3-11e6-90ce-26a94dd18ab8.png)

purple
![theme-purple](https://cloud.githubusercontent.com/assets/18008302/21227757/e2ecf79a-c2e3-11e6-9140-68a08d1acd12.png)

ruby
![theme-ruby](https://cloud.githubusercontent.com/assets/18008302/21227758/e2f1015a-c2e3-11e6-90ea-241f2c7d2f94.png)

sky
![theme-sky](https://cloud.githubusercontent.com/assets/18008302/21227759/e2f14c96-c2e3-11e6-90b9-cb36a150ab4f.png)

**Comment by NickIliev** [comment]
@realtebo see the updated info above ^^^

**Comment by realtebo** [comment]
Yes, I can confirm that is working adding explicit action bar and removing the explicit inclusion of app.css, thanks 

I was expecting that button would be purple in the purple theme, lol. 

Actually, I'm playing (succesfully) with SASS, so I'll fix every colors.
Close, if you want.

**Comment by NathanWalker** [comment]
You can also refer to this image for how each colored theme will look (actionbar + button):
http://docs.nativescript.org/img/theme/color-schemes-all.png

If you have a subscription to egghead.io, this SASS video specifically details working with the core theme:
https://egghead.io/lessons/angular-2-create-a-custom-app-theme-using-sass-for-nativescript
