### ISSUE TITLE
Missing back shadow of ActionBar when class="action-bar" is applied

### ISSUE THREAD

**Issue by vchimev** [NativeScript/theme#125]
Thanks to @myninka,
we noticed that if `class="action-bar"` is applied, there is missing back shadow of the ActionBar component in Android.

The following snippet
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
    <Page.actionBar>
        <ActionBar title="My App" icon="" class="action-bar">
        </ActionBar>
    </Page.actionBar>
</Page>
```
looks like
![screen shot 2017-01-04 at 3 38 10 pm](https://cloud.githubusercontent.com/assets/12251337/21643992/e95b6926-d293-11e6-9a83-b14427243cf5.png)

The following snippet
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
    <Page.actionBar>
        <ActionBar title="My App" icon="">
        </ActionBar>
    </Page.actionBar>
</Page>
```
looks like
![screen shot 2017-01-04 at 3 38 22 pm](https://cloud.githubusercontent.com/assets/12251337/21643989/e759c6e0-d293-11e6-8344-0bafdd08960e.png)

**Comment by bradmartin** [comment]
Related core issue: https://github.com/NativeScript/NativeScript/issues/1799

**Comment by vchimev** [comment]
Ah, I was wondering why this issue looks so familiar ...

It is already fixed in master of tns-core-modules, available in *next* version and will deliver officially in 2.5.0.

Thanks, @bradmartin!
