### ISSUE TITLE
Style the default Android transition

### ISSUE THREAD

**Issue by vchimev** [NativeScript/theme#128]
Hi Guys,

I gave a try to the dark theme applied on the `ng` template.

Everything looks great, I am just wondering how could change the color of the default transition on Android. Currently, while navigating to the items and back, there is white transition.

How could it be avoided? Could it be styled by the theme?

Many thanks,
vchimev

**Comment by bradmartin** [comment]
Is the default transition `fade`? I haven't looked into doing anything with it personally, but I do recall if you don't specify the transitionDuration for a `fade` transition it was a quick white flash on the screen.

**Comment by NickIliev** [comment]
@vchimev  @bradmartin I have struggled with this, and I think it is not possible to style the activity that appears behind the pages during a transition. More info on that from @hshristov

**Comment by danielgek** [comment]
@vchimev @bradmartin i have made a custom transition, you can take a look [here](https://gist.github.com/danielgek/d3d7812bd3ed9793efadabdebbec6c4e)
