### ISSUE TITLE
Outdated or unclear documentation

### ISSUE THREAD

**Issue by renestalder** [NativeScript/theme#129]
The documentation on nativescript.org isn't clear, at least for me.
http://docs.nativescript.org/ui/theme

Light and dark themes don't exist in the form mentioned in the documentation.

```css
@import 'nativescript-theme-core/css/core.light.css';
```

The CSS folder only have OS specific files, thus IDE like WebStorm say, the file doesn't exist. I assume the CLI handles this, so there should be any note about this in the documentation.

**Comment by NathanWalker** [comment]
@renestalder thank you for the question.
I have found both:
```
@import 'nativescript-theme-core/css/core.light.css'; 
// and
@import 'nativescript-theme-core/css/core.dark.css';
```
as stated in the docs to exist and work fine.
Perhaps this is a WebStorm specific issue? Not sure, could you provide any more info here?

**Comment by NathanWalker** [comment]
I assume WebStorm is trying to resolve that path relative to the app which NativeScript actually pulls those imports from `node_modules` folder so maybe there is a way to configure WebStorm for that?

**Comment by renestalder** [comment]
Yes, it works. That's not what I mean.

But I'm either completely blind or don't understand node module resolving, but the fact is, when I look at the node_modules folder or to this repository, I can't find a file "core.light.css" in the CSS folder. That's also why Webstorm/PHPStorm can't resolve it.

I never seen that before in a npm package. What do I misunderstand here?
