### ISSUE TITLE
Image pressed state

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/theme#134]
Hi!,

Many times I need use a Image as button. Can I change image state when pressed, like I do using android image states? 

Thanks!

**Comment by byhba** [comment]
Hi,
I have the same issue. How to change image button on pressed, and back to the first image on key up?

Thanks

**Comment by rdlauer** [comment]
I recommend you ask this question on the [NativeScript community forum](https://discourse.nativescript.org/).
