### ISSUE TITLE
Buttons on Android have their text cut off at the bottom

### ISSUE THREAD

**Issue by calebkiage** [NativeScript/theme#138]
![capture _2017-08-22-16-23-47](https://user-images.githubusercontent.com/747955/29610129-e9f93e0c-8801-11e7-889f-84fe8bdcadd4.png)
when using btn-outline, the text is cut off as shown in the image. Setting the height to auto on the element fixes this issue but makes the btn-outline taller than the btn-primary.

**Comment by csimpi** [comment]
@manoldonev Why is this closed? Still an issue for me

**Comment by dmedina2015** [comment]
Not having the problem with "-outline", but I do get it with "-rounded-xx". @manoldonev , could you reopen the issue?

**Comment by Zryru** [comment]
same here @manoldonev 

`<Button class="-primary -rounded-lg" ></Button>`

android 
![image](https://user-images.githubusercontent.com/31626435/120934872-6bf3cf80-c700-11eb-9b0e-39c53e9308b6.png)
