### ISSUE TITLE
Couldn't run with errors

### ISSUE THREAD

**Issue by LHLK** [NativeScript/theme#142]
Hello there,
I cloned the package and run with tns run android (Win 10).  The following errors shown up:
Errors:
 tns-android@3.3.1
added 1 package in 2.073s
Project successfully created.

E:\Project\Training\NativeScript\Tutorial\theme-master\theme-master>tns run android
Searching for devices...
Starting Android emulator with image Nexus5
Waiting for emulator device initialization....
Executing before-prepare hook from E:\Project\Training\NativeScript\Tutorial\theme-master\theme-master\hooks\before-prepare\nativescript-dev-sass.js
Found peer node-sass
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        node_modules/bootstrap/scss/_variables.scss:142, in function `darken`
        node_modules/bootstrap/scss/_variables.scss:142
        on line 142 of node_modules/bootstrap/scss/_variables.scss
>> $link-hover-color:          darken($link-color, 15%) !default;
   ----------------------------^

Unable to apply changes on device: emulator-5554. Error is: SASS compiler failed with exit code 1.

My tns version is 3.3.1.  Please kindly take a look.

Thanks.
LH

**Comment by joeizy** [comment]
Also tried with tns version 3.4.0

**Comment by joeizy** [comment]
Fixed this by changing the bootstrap version in package.config to "4.0.0-alpha.6".

```
{
  "name": "nativescript-theme-core",
  "version": "1.0.4",
  "description": "Telerik NativeScript Core Theme",
  "homepage": "https://www.nativescript.org",
  "license": "Apache-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/theme"
  },
  "nativescript": {
    "id": "org.nativescript.theme",
    "tns-android": {
      "version": "2.5.0"
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "bootstrap": "4.0.0-alpha.6",
    "nativescript-dom": "^1.0.9",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-telerik-ui": "^1.6.2",
    "nativescript-themes": "^1.1.0",
    "tns-core-modules": "~2.5.2"
  },
  "devDependencies": {
    "babel-traverse": "6.13.0",
    "babel-types": "6.13.0",
    "babylon": "6.9.0",
    "glob": "^7.0.5",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.1.0",
    "nativescript-dev-typescript": "~0.4.2",
    "node-sass": "~4.5.2",
    "sass-lint": "^1.10.2",
    "typescript": "~2.1.0"
  },
  "scripts": {
    "builder": "node scripts/builder.js"
  }
}
```

PR: https://github.com/NativeScript/theme/pull/143

**Comment by rdlauer** [comment]
@joeizy FYI I tried changing the bootstrap version as you noted, but I don't see any difference. I see the same error as before.

**Comment by joeizy** [comment]
@rdlauer thanks for taking a look. I pulled down my branch again and confirmed it does work, but while doing so I first had the error above. The error went away after I ensured my workspace was clean.

```
git reset --hard
git clean -xfd
```

After doing this and re-running `tns run ios` my `package-lock.json` showed I was pulling the right bootstrap version.
```

    "bootstrap": {
      "version": "4.0.0-alpha.6",
      "resolved": "https://registry.npmjs.org/bootstrap/-/bootstrap-4.0.0-alpha.6.tgz",
      "integrity": "sha1-T1TdM6wN6sOyhAe8LffsYIhpycg=",
      "requires": {
        "jquery": "3.3.1",
        "tether": "1.4.3"
      }
    },
```

Would you please try again and ensure you have a clean working directory? You can also try checking out the branch from my fork (that was only created to submit the fix): https://github.com/joeizy/theme/tree/fix-bootstrap-sass

**Comment by joeizy** [comment]
BTW I'm on tns CLI 3.4.1 now but as mentioned, it worked on 3.4.0 as well.

**Comment by rdlauer** [comment]
@joeizy That was it, something must've been cached somewhere that I missed! Anyway +1 to me on this fix.

@NathanWalker can you accept his PR to at get this functioning again?
