### ISSUE TITLE
Support for "markingMode" flag

### ISSUE THREAD

**Issue by RinkalGohel** [NativeScript/theme#149]
Hi there!

Wanted to know whether your plugin will still be working fine if I add the flag of 'markingMode' set to 'none' in package.json file, as mentioned in one of the blogs of NativeScript release?

Here is the link of the blog where the reference is made for the same: https://www.nativescript.org/blog/announcing-the-release-of-nativescript-3.2

Looking forward to an early reply. Thank you!

**Comment by etabakov** [comment]
The theme doesn't involve an native code on its own, so markingMode: none shouldn't affect the behavior of this plugin.
