### ISSUE TITLE
demo app not 6.0 compat

### ISSUE THREAD

**Issue by rynop** [NativeScript/theme#156]
The [6.0 announcement](https://www.nativescript.org/blog/announcing-nativescript-6.0---webpack-all-the-way-seamless-app-updates-new-core-theme-and-a-lot-more) states to head to this repo to test out the demo app, however when I try to run it I get the following error:

> The current application is not compatible with NativeScript CLI 6.0.

Is the `/app` dir in this repo not the demo app?

**Comment by NathanWalker** [comment]
I think they meant this branch:
https://github.com/NativeScript/theme/tree/next

**Comment by bundyo** [comment]
Indeed. I should merge in master one of these days.

**Comment by rynop** [comment]
Yea prob makes sense with the timing of the 6.0 release going GA

**Comment by rynop** [comment]
FWIW I can't get `next` to work.

```
~/p/theme (next|✚1…) $ git branch
  ls
  master
* next
~/p/theme (next|✚1…) $ npm install
...
The current project contains a webpack.config.js file located at /Users/ryan/projects/theme/webpack.config.js that differs from the one in the new version of the nativescript-dev-webpack plugin located at /Users/ryan/projects/theme/node_modules/nativescript-dev-webpack/templates/webpack.javascript.js. Some of the plugin features may not work as expected until you manually update the webpack.config.js file or automatically update it using "./node_modules/.bin/update-ns-webpack --configs" command.
...

tns run ios
Searching for devices...
Cannot find module 'nativescript-dev-sass/lib/before-prepare.js'
```

```
~/p/theme (next|✚1…) $ tns --version
6.0.1
~/p/theme (next|✚1…) $ node --version
v10.16.0
~/p/theme (next|✚1…) $ npm --version
6.9.0
```
