### ISSUE TITLE
ActionBar

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#16]

**Comment by NathanWalker** [comment]
@bradmartin I need your help styling the `ActionItem` in Android. I'm not sure how to get rid of the shadow here...
<img width="420" alt="screen shot 2016-08-23 at 10 36 45 pm" src="https://cloud.githubusercontent.com/assets/457187/17919467/a2819e96-6982-11e6-81c8-7428d91efeee.png">

You will find the android style for that here:
https://github.com/NativeScript/theme/blob/master/app/scss/themes/core/platforms/_action-bar.android.scss
I tried `border:0` but not sure how to completely remove that shadow?

**Comment by bradmartin** [comment]
Try border width = 0.1 let me know if that works or not.
