### ISSUE TITLE
#ask NativeScript Theme 2.0 demo (TYPESCRIPT)

### ISSUE THREAD

**Issue by budiantokang** [NativeScript/theme#161]
Hi, i am trying to use NS 6 now. but i want to use version 2.0.2 theme and i already try so long the time still cant work it, is there have any sample demo who can i learn it?
Thank's..

**Comment by bundyo** [comment]
Should be the same for TypeScript as for JavaScript - import the JS file and the two SCSS or CSS file, depending on what you use.
