### ISSUE TITLE
SASS theme import not working

### ISSUE THREAD

**Issue by CoooWeee** [NativeScript/theme#165]
Npm (6.10.2) install of 
    `"nativescript-theme-core": "^2.0.5"`
is missing files in folder "scss". 

The folder only includes:
`_controls.scss  _index.scss     _variables.scss bootstrap       core            mixins          skins`

**To reproduce do own SCSS which includes a nativescript-theme-core import:**
`@import ~nativescript-theme-core/scss/dark'`

**Are there any errors/warnings logged in your browser console?**

```
ERROR in ./app.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):

@import '~nativescript-theme-core/scss/dark';
^
      File to import not found or unreadable: ~nativescript-theme-core/scss/dark.
```

**Comment by markosole** [comment]
Same thing here. In my case is "light" instead of dark but same thing.

**Comment by bundyo** [comment]
Please read the readme - there is no light/dark files in 2.0 beta.

**Comment by markosole** [comment]
Thanks for response. I'm not using dark/light themes. I am trying to revert BACK to v.1.0.6 and get my styles back. Update messed up something and my stiles are not in use any more.

Latest error I am getting is
WARNING in ./app.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):
File to import not found or unreadable: ~nativescript-theme-core/scss/platforms/index.android.
      in C:\Users\masterx\Documents\NativeScript\sidekick\violeta\prodexapp\app\app.scss (line 7, column 1)
 @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$) ./app.scss
 @ ./app.js

**Comment by bundyo** [comment]
Delete the platforms folder, make sure you've installed 1.0.6 and try rebuilding again.

**Comment by markosole** [comment]
Perfect, got everything back as it was before upgrade. tns platform clean android was not helping, I tried that before. As you said, removing platform folder is needed.

**Comment by bundyo** [comment]
I'll try to reproduce it and report it to the CLI team.

**Comment by isawk** [comment]
Followed readme, getting below errors

```
@import "~nativescript-theme-core/core";
@import "~nativescript-theme-core/blue";
```

Above import, produces below errors

```
ERROR in ./app.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):

@import './scss/core';
^
      File to import not found or unreadable: ./scss/core.
      in ../node_modules/nativescript-theme-core/core.scss (line 8, column 1)
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
 @ ./main.ts
Executing webpack failed with exit code 2
```

**Comment by m-abs** [comment]
I'm getting the same error as @isawk

**Comment by bundyo** [comment]
Hmm, this looks like a very possible issue in node-sass. I'll try fixing it as soon as possible.

**Comment by bundyo** [comment]
Just tried it here and it works fine with node-sass too. Can you give me more details about your previous setup?

**Comment by CoooWeee** [comment]
I used:
"nativescript-theme-core": "2.0.19"
"node-sass": "4.12.0"

On an scss-file with at the first line:
`@import "~nativescript-theme-core/core";`

I get:
 "message": "File to import not found or unreadable: ~nativescript-theme-core/core.",
I wonder why he looks for "core." and not "core.scss" which would exist.

**Comment by bundyo** [comment]
Hmm, might have introduced a node-sass incompatibility by mistake.

**Comment by bundyo** [comment]
Can you check if it works with 2.0.20?

**Comment by CoooWeee** [comment]
@bundyo : same issue with 2.0.20.
Might be something else. I tried Ruby Sass 3.7.4:

`sass ./app/_app-variables.scss --trace `

> ./app/_app-variables.scss:10: File to import not found or unreadable: ~nativescript-theme-core/core. (Sass::SyntaxError)
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:67:in `rescue in import'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:44:in `import'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:28:in `imported_file'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/import_node.rb:37:in `css_import?'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:310:in `visit_import'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/exec/sass_scss.rb:396:in `run'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/exec/sass_scss.rb:63:in `process_result'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/exec/base.rb:50:in `parse'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/lib/sass/exec/base.rb:18:in `parse!'
> 	from /Library/Ruby/Gems/2.3.0/gems/sass-3.7.4/bin/sass:13:in `<top (required)>'
> 	from /usr/local/bin/sass:22:in `load'
> 	from /usr/local/bin/sass:22:in `<main>'

**Comment by CoooWeee** [comment]
@bundyo: sorry, works fine. Thanks. Please close.

**Comment by bundyo** [comment]
It was already closed. :smile:
