### ISSUE TITLE
Added styles in _app-common.scss are not loaded after update to 2.0

### ISSUE THREAD

**Issue by markosole** [NativeScript/theme#166]
Hi all,

I've updates theme to latest 2.0.x and my styles have been changed. Everything I defined manually in _app-common.scss is not in use any more. Maybe something else is "broken" and style is not getting applied.

**Comment by bundyo** [comment]
Can you post where do you load _app-common.scss and where and how do you load the theme?

**Comment by markosole** [comment]
Everything is by default, what I got from basic template downloaded using Sidekick. _app-common.scss, app.android.scss, app.ios.scss are located in app root folder.

**Comment by bundyo** [comment]
In 2.x beta you don't need app.android.scss and app.ios.scss. You need one app.scss file that imports the variables in _app-common.scss and after that - the theme files as per the readme. However, reverting back to 1.0.6 for now might be better for you, until we fix the templates, when the theme gets released in 6.1.

**Comment by markosole** [comment]
Thanks for explanation. Documentation https://docs.nativescript.org/ui/theme is missleading than. Beta likes to break things, I'll stay away for now.

**Comment by bundyo** [comment]
Docs are not yet updated, since 2.0 is still in beta. Currently for 2.0 you need to follow the readme here.
