### ISSUE TITLE
File not found - scss/patforms/index.ios.scss

### ISSUE THREAD

**Issue by netwobble** [NativeScript/theme#169]
File not found - scss/patforms/index.ios.scss
File not found - scss/patforms/index.android.scss
Received error...
*****************
ERROR in ./app.scss
Module build failed (from ../node_modules/sass-loader/lib/loader.js):
*****************
undefined
^
      File to import not found or unreadable: ~nativescript-theme-core/scss/platforms/index.ios.
      in ... /src/app.scss (line 8, column 1)
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65
 @ ./main.tns.ts

*****************
reference is in the app.ios.scss file
*****************
@import '~nativescript-theme-core/scss/index';

*****************
Following configurations from package.json
*****************
  "dependencies": {
    "@angular/animations": "~8.2.2",
    "@angular/common": "~8.2.2",
    "@angular/compiler": "~8.2.2",
    "@angular/core": "~8.2.2",
    "@angular/forms": "~8.2.2",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.2",
    "@angular/platform-browser-dynamic": "~8.2.2",
    "@angular/router": "~8.2.2",
    "core-js": "2.5.4",
    "nativescript-angular": "~8.2.0",
    "nativescript-theme-core": "~2.0.5",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular/cli": "~8.2.2",
    "@angular/compiler-cli": "~8.2.2",
    "@angular-devkit/build-angular": "~0.802.2",
    "@nativescript/schematics": "~0.7.0",
    "@nativescript/tslint-rules": "~0.0.2",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.7.2",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nativescript-dev-webpack": "~1.1.0",
    "protractor": "~5.4.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3",
    "node-sass": "^4.7.1"
  }

**Comment by bundyo** [comment]
Please search before opening a new issue. Theme 2.0 **beta** is not compatible with Theme 1.0.x and is not used the same way. Check the readme for how to use it or downgrade until it is final.
