### ISSUE TITLE
Invalid Version: next

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#175]
When I run `tns plugin update nativescript-theme-core` on new NativeScript apps I get the following error.

```
+ nativescript-theme-core@2.0.9
added 1 package from 1 contributor and audited 9960 packages in 3.666s
found 0 vulnerabilities

Invalid Version: next
```

The update and installation still works, but it looks like it doesn’t because of this error. Maybe it doesn’t like the platforms being set to `"next"`?

**Comment by bundyo** [comment]
This is problem with CLI - when the platform is already installed, it doesn't update the version in the package or detect the installed version when sending to the device. I'll report it to them. The "fix" is to remove the platforms folder and CLI will update the version with the latest one.

**Comment by bundyo** [comment]
Updated to 6.1.0 as it got released already. Closing.
