### ISSUE TITLE
Theme 2.0 Material design issues

### ISSUE THREAD

**Issue by derschnee68** [NativeScript/theme#182]
Hello,

When using nativescript-themes 2.0.1 and tns-core-modules 6.1.1, and material design theme
the slider, progress and switch components are badly designed (weird effect on tap event for switch).

Source: the demo app from this repo.

Thank you for the great work :)

![70361784_2405837819686428_31645632569540608_n](https://user-images.githubusercontent.com/12176105/65271088-c27c3d00-db1c-11e9-9cd0-aee2d6ebd22d.jpg)
![70695661_479382829577390_2324161774875574272_n](https://user-images.githubusercontent.com/12176105/65271094-c4460080-db1c-11e9-8276-8f0ffb73f179.jpg)
![70954274_763213110798372_2093096133533368320_n](https://user-images.githubusercontent.com/12176105/65271097-c5772d80-db1c-11e9-8ba0-37688aaaee8d.jpg)

**Comment by StefanAleksik** [comment]
I have the same issue with <Progress />

**Comment by bundyo** [comment]
I'll take a look if things can be improved.

The main issue with the Material design theme is that it is expected to be always white (at least in Kendo). I'll check if I can get the palettes from the the real material design project, now that the dark mode has gone official in Android 10.

**Comment by bundyo** [comment]
Closing with 2.0.24
