### ISSUE TITLE
iOS Modal Dialogs have incorrect text color in Dark mode

### ISSUE THREAD

**Issue by kfisto** [NativeScript/theme#184]
Using the included sample app, Change to the Dark theme, then navigate to the Dialogs page and tap Show Alert.

Expected: Dark modal window with lighter text
Actual: Dark modal window with dark gray text that's barely visible

I tried to test this in android, but the demo app currently fails to launch.

**Comment by bundyo** [comment]
Is this only in the Theme or also happens without it? Currently not sure dialogs  can be styled at all. Can you check?

**Comment by kfisto** [comment]
Our trunk which is using theme 1.0.6 results in dialogs with white text over a dark background. It does seem that something in v2 is causing the text color to be incorrect. For clarity's sake, I'm not trying to set a specific text color, but we do need the dialogs to be legible.

**Comment by bundyo** [comment]
Thanks, I'll check it out.

**Comment by bundyo** [comment]
Should be fixed in 2.0.23

**Comment by mcgouganp** [comment]
This does not appear to be fixed.

If you have an iOS device in Dark Mode and run the test app for the theme it shows the Alert button as a very dark and just readable blue.

However if you change app.scss to import another theme, (I was testing with Sky), then the Alert button is almost invisible. 

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-21 at 20 59 33](https://user-images.githubusercontent.com/1724689/72799448-fb761b00-3c90-11ea-8fef-6f9a77030faf.png)

**Comment by erjdriver** [comment]
Any progress on this - has been a few months...

**Comment by bundyo** [comment]
Not much time lately, probably next week will have time to look at latest issues.

**Comment by erjdriver** [comment]
Any headway on this issue?

Dark mode in ios is not usable.

**Comment by erjdriver** [comment]
When can we expect this issue to be fixed?

Over nine months!

It's a relatively high priority issue since it makes ios dark mode almost unusable.

**Comment by erjdriver** [comment]
Hello...anyone there??

Just a placeholder before the bot closes the issue.

**Comment by grey280** [comment]
Bump - been banging my head against the same issue on the `action` variant to no avail.

**Comment by erjdriver** [comment]
Almost coming to the 1 year anniversary of this bug.

I don't like to pre-suppose other people's bugs as easy to fix etc - but isn't this a constant somewhere in the plugin.

I've looked and for the life of me - I can't find it - must be an ios system default it's using.

Anyway - fix appreciated!

**Comment by grey280** [comment]
@erjdriver sounds like you may want to open a PR against NativeScript/NativeScript; I believe [this](https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/dialogs/dialogs.ios.ts) is the file to make the changes in?

**Comment by sivo1981** [comment]
Any ETA when this [https://github.com/Rob4226/NativeScript/commit/f373b5d50e91eb631463f92bda54aeb2c875402d](url) commit is getting merged and new version released.

**Comment by jelledijkstra97** [comment]
This issue still isn't solved. Any updates?

**Comment by OPADA-Eng** [comment]
any updates on this?

**Comment by NathanWalker** [comment]
Resolved in @nativescript/core 8.5
