### ISSUE TITLE
Colorize

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#185]
I'm trying to set the background color of an element - based on the active theme.

`.test
{
@include colorize($background-color: background 40%);
}
`

I want the color to be 40% lighter/darker than the current background color.

The above is not working.

Any help/documentation on this mixin.

**Comment by bundyo** [comment]
Will do tomorrow. Try with 

```scss
.test { 
    @include colorize($alternate-background-color: background 40%);
} 
```

**Comment by erjdriver** [comment]
Thank you - I appreciate the help.

I looked at the colorize.scss mixin and was stumped with the code - specifically the prefixes like alternate and contrast etc.

Any documentation would help.

Also, being new to scss, I see `background` used w/o the $ - are those the same???
