### ISSUE TITLE
First disabled TextField/TextView in a modal dialog not styled correctly

### ISSUE THREAD

**Issue by joshcomley** [NativeScript/theme#187]
Please see example project:

https://www.dropbox.com/s/7s9cpmivx9s01vm/ns-disabled-bug.zip?dl=1

I have `TextField` and `TextView` elements that are disabled, all with a class name `example-text-box`.

In `_app-common.scss` I have:

    .example-text-box:disabled {
        color: red;
    }

I am rendering the text fields in `home.component.html` as well as in a modal (`example-dialog.component.html`), and this is the result:

`home.component.html`:
![Screenshot_20191002-174348_nsdisabledbug](https://user-images.githubusercontent.com/820534/66063990-74176700-e53c-11e9-88af-4100090af94b.jpg)

`example-dialog.component.html`:
![Screenshot_20191002-174342_nsdisabledbug](https://user-images.githubusercontent.com/820534/66064005-7d083880-e53c-11e9-9af1-e8061084b543.jpg)

Not much more to add!

**Comment by joshcomley** [comment]
Hi, thanks for taking a look. It's on a Samsung SM-T585 (Samsung Galaxy Tab A, 2016). I'll try it on something else - I hadn't actually done that because it reproduced so cleanly in the sample app for me!

**Comment by bundyo** [comment]
Closing this until you investigate. Please reopen if needed.
