### ISSUE TITLE
Primary color not applying correctly using Kendo UI themes

### ISSUE THREAD

**Issue by mukaschultze** [NativeScript/theme#188]
Primary color does not apply properly to buttons when using themes downloaded from Kendo UI theme builder.

### No custom theme / Default Kendo UI theme / Material / Bootstrap

![theme](https://user-images.githubusercontent.com/13923364/66330711-50229f80-e907-11e9-8e0f-78f29d7e7520.png)

## How to reproduce:

Add  the following variables to the `variables.scss` file:

```scss
$base-theme:Material;
$skin-name:teste;
$swatch-name:Material;
$border-radius: 2px;
$primary-palette-name: indigo;
$secondary-palette-name: pink;
$theme-type: light;

@import '~nativescript-theme-core/index';
```
and to any html:
```html
<Button text="Button -primary" class="-primary"></Button>
<Button text="Button -secondary" class="-secondary"></Button>

<Button text="Button btn btn-primary" class="btn btn-primary"></Button>
<Button text="Button btn btn-secondary" class="btn btn-secondary"></Button>
```

**Comment by bundyo** [comment]
I've pushed some fixes. Can you check the app in master if now the Kendo themes look better?

On a side note - currently there's no -secondary modifier in {N} theme. Do you want one? In the original skins it can point to the ActionBar background color, as there's no other accent color in them.

**Comment by mukaschultze** [comment]
The primary color is working fine, thanks!

There's one small inconsistency that I found out, the tap highlight is a little different using the compat classes:
![Peek 09-10-2019 13-13](https://user-images.githubusercontent.com/13923364/66499637-93f7df00-ea96-11e9-93d1-66c705726351.gif)

The `-secondary` is there just for demo purposes.

**Comment by bundyo** [comment]
Hmm, completely forgot - if you target compat theme, you should add $compat: true to your Kendo vars file. Should add it to the docs.

Can you check if this fixes it?

**Comment by bundyo** [comment]
Closing with 2.0.24
