### ISSUE TITLE
Complete list of CSS properties for new theme?

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/theme#210]
Is there a full list of CSS properties available for us to peruse with the new core theme? Either in github or an updated doc?

**Comment by bundyo** [comment]
If you mean custom CSS properties (CSS variables) - they are listed in the README here:
https://github.com/NativeScript/theme#css-variables

Keep in mind they are only exported in the skins, not in core theme.

**Comment by rdlauer** [comment]
I guess I mean any custom properties, kind of like what we show here:

https://docs.nativescript.org/ui/styling#nativescript-specific-css-properties

I realize we are basing the new theme on element selectors, but in the previous core theme, I _think_ we had some classes like `img-rounded` or `thumb` that you would still have to explicitly add to an element to see the results.

To me having one styling doc that shows supported css properties, custom properties unique to {N}, and any additional core theme properties would be super useful.

**Comment by bundyo** [comment]
This will be added to the README soon.
