### ISSUE TITLE
iOS 13 completely broke my app

### ISSUE THREAD

**Issue by edmundpf** [NativeScript/theme#211]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2
 - Plugin(s): nativescript theme core v1.0.4

**Describe the bug**

Had working app with proper styles. When running app on iOS 13 app styles are non-existent, no buttons, text everywhere, icons missing, white screen, etc.

**To Reproduce**

Update iOS to v13 and launch nativescript app (same result in normal mode or dark mode)

**Expected behavior**

App retains same styles as before update.

**Sample project**

**Additional context**

Was using nativescript theme core 1.0.6 as nativescript theme core v2+ had breaking changes.

**Comment by bundyo** [comment]
There are multiple changes to colors in iOS 13, which are handled by the upcoming {N} 6.2 release and Theme 2.x. To avoid breaking in dark mode until you fix it, you can restrict your app to only use light mode for now. Check out this link for more info:
https://stackoverflow.com/a/56546554

**Comment by edmundpf** [comment]
> There are multiple changes to colors in iOS 13, which are handled by the upcoming {N} 6.2 release and Theme 2.x. To avoid breaking in dark mode until you fix it, you can restrict your app to only use light mode for now. Check out this link for more info:
> https://stackoverflow.com/a/56546554
Thanks, it's not applying any styles in light or dark mode at all, it seems to be the same as this issue where the app.css is not imported at all, for example, my prior font-awesome icons show as question marks, etc. 

https://stackoverflow.com/questions/58103647/render-icon-in-button-text-nativescript-6-1-1-and-ios-13-xcode-11

**Comment by bundyo** [comment]
This looks like a different issue. Can you post the errors CLI gave you on iOS? Looks like all the CSS was not loaded.

**Comment by edmundpf** [comment]
This is all I received, I tried updating my tns-core-module as suggested from another post to remedy this, the app was still built on the phone however:

[19-10-30 12:32:12.118] Error detected during LiveSync on 516c25a98591d68535f587e6f0430e482e693101 for C:\Users\EPfeil\Documents\Ubuntu\scripts\javascript\kaiser-dash-js. Error: Could not start service com.apple.mobile.house_arrest

**Comment by bundyo** [comment]
This looks like a something specific to {N}, not the theme. Can you try asking in the Community Slack?

**Comment by edmundpf** [comment]
> This looks like a something specific to {N}, not the theme. Can you try asking in the Community Slack?

sure
