### ISSUE TITLE
How to use the "Kendo UI Theme builder"

### ISSUE THREAD

**Issue by elonmallin** [NativeScript/theme#219]
**Is your feature request related to a problem? Please describe.**
I have no idea how I should use the Kendo UI Theme Builder as explained briefly in the readme: https://github.com/NativeScript/theme#kendo-ui-themebuilder-support

**Describe the solution you'd like**
I'd like to know what I can expect after I go and create a theme, get my `all.css` and `variables.scss` and include them in my project.

I would expect that the `$accent` color should be used for my primary buttons (`<Button class="-primary">`) since it is in the preview on the theming website.

Maybe I'm just doing something wrong but I tried setting the `$accent` color all over that I can think of, before and after including the core theme and everywhere in between.

Maybe the `$accent` isn't even supposed to set the button color? But then the documentation is misleading I'd say.

**Describe alternatives you've considered**
I tried finding information about how to style the `-primary` button using themes but I don't know where I should do it. I assume I shouldn't just go and
```scss
.-primary {
  background-color: red;
}
```
in my main scss file since the `$accent` color is for theming and I would like to be able to swap out themes.

**Additional context**
I just want to be able to use custom themes.

**Comment by bundyo** [comment]
The $accent color is used for your primary Buttons, but you should set it before loading the theme, since it initializes some internal structures and changing it later won't have the desired effect.

For instance, like this:

```scss
// Colors
$accent: red;
$complementary: green;

// Core styles
@import '~@nativescript/theme/index';
```

If you want to import variables from the theme first, do it like this:

```scss
// Core variables
@import '~@nativescript/theme/scss/variables';

// Colors
$accent: const(ruby);
$complementary: const(purple);

// Core styles
@import '~@nativescript/theme/index';
```

**Comment by elonmallin** [comment]
Thanks, that works =)

Where is `$complementary` used btw? It's not in the theme colors from the Theme Builder.

I also noticed that if I want to include my own variables in a component and just import the `app.scss`  things break like the colors in the `ActionBar` here: https://play.nativescript.org/?template=play-ng&id=g3sJxD&v=2

I have to make sure to split up my variables and theme imports to be able to use variables in my components like:
**my-variables.scss**
```scss
// Theme variables
$accent: red;
// ...more

@import '~@nativescript/theme/scss/variables';
```

**app.scss**
```scss
@import './my-variables';
@import '~@nativescript/theme/index';

// Custom styles...
```

**my.component.scss**
```scss
@import '~/my-variables';

// Component styles...
```

I think that should be included somewhere in the documentation or the example in the README should recommend a structure like this where you can import all variables in a component without problems.

**Comment by bundyo** [comment]
The problem in Playground is due to specificity. Unfortunately currently in {N} there's no good style debugging in DevTools, so you can't see that some ActionBar Label styles have a specificity of 11, so you need to up with one to work. Check this updated Playground:

https://play.nativescript.org/?template=play-ng&id=g3sJxD&v=4

**Comment by elonmallin** [comment]
Where is the specificity? I don't see any difference in out code yet your works. Did you change it in the `@nativescript/theme`?

**Comment by bundyo** [comment]
No, I've just added an ActionBar before your two selectors, which rises their specificity with 1. :)

**Comment by elonmallin** [comment]
Ah I see. That made me realize something, this makes it so that overriding things on a `-primary` button you have to do: `Button.my-override-class` to be specific enough otherwise `-primary` will win.

This would be nice if it was emphasized in the docs, I guess especially since we started off with `btn-primary` and ppl assume it would work similar to bootstrap.

This is a playground to show that the specificity is needed to override a `<Button class="-primary">`: https://play.nativescript.org/?template=play-ng&id=g3sJxD&v=5

**Comment by bundyo** [comment]
Well, yeah, I thought this was common knowledge in CSS styling, but still we will link some articles on the subject.

**Comment by bundyo** [comment]
Forgot to tell you that $complementary is the old $ab-background variable - the background color of the ActionBar. We decided that this color is some kind of accent that people may want to use more generically throughout their app, so we renamed it to $complementary.

**Comment by elonmallin** [comment]
It is common knowledge I would assume. It's just a bit unintuitive coming from bootstrap which you have similarities with. Starting out with `btn-primary` that is the same in bootstrap. Then going to `Button.-primary` now we're forced to specify everything we do on a button with `Button.my-class` to make sure we at least override nativescripts basic styles.

That caught me off guard with the `ActionBar .accent` thing in the playground too.

Guess it's not that much of a problem, more the mindset coming from bootstrap which was working before the upgrade to v2 themes.

Or maybe it would be slightly problematic if you want to have generic styles like `.p-x-10` work for everything. You'd have to create this class with specificity for everything that exists for it to work right?
```scss
Button.p-x-10 { ... }
Label.h1.p-x-10 { ... }
ActionBar .action-bar-label.p-x-10 { ... }
```
Just declaring the plain `.p-x-10` after the components instead wouldn't work anymore like I think we talked about earlier?

**Comment by bundyo** [comment]
I've tried to make the specificity of the theme styling as low as possible. However at places and specific components this is not really achievable in this moment. For instance dark mode in web is done with @media scopes, but we don't have these in {N}, so we had to do that through a class. This class raises the specificity of all dark selectors with 10 and there's nothing that can be done until @media support is added. That's just an example. 

The example you're mentioning is not working pure to selector placement inside the Theme. Unfortunately I didn't notice it until the release and now this would be a breaking change. So we would do it, but for the next major version.

**Comment by SuperdanTX** [comment]
On the same subject, @import '~@nativescript/theme/index'; has not worked for me.
I have to use @import "nativescript-theme-core/scss/core/_index"; in order to get v2 to work.
This was an upgrade on an existing product.
Wondering if this is an upgrade issue, or something else?
I place this question this here, because the resulting question led to this very post, and hopefully being answered here would be insightful for others.

**Comment by bundyo** [comment]
Which package and version are you using?

**Comment by SuperdanTX** [comment]
CLI: 6.3.3
Cross-platform modules:
Android Runtime: 6.5.0-2020-03-12-133513-01
iOS Runtime: 6.5.0-2020-03-12-110223-01
and
"nativescript-theme-core": "^2.0.24"

**Comment by bundyo** [comment]
"nativescript-theme-core" is the old Theme package name, which is now deprecated. The new one is "@nativescript/theme", latest version is 2.3.3 - try with that.

**Comment by SuperdanTX** [comment]
Ok, I think we may be getting to the root of the issue here. When I run tns plugin update nativescript-theme-core, I still get 2.0.24. What am I missing for upgrading the version? Again, thanks for the help.

**Comment by bundyo** [comment]
The name of the package? You need to change it, in order to update.

**Comment by SuperdanTX** [comment]
Sometimes it's the easiest stuff that's the hardest lol.
Thanks for correcting me.
npm install @nativescript/theme --save did the trick.
Any need to remove the "nativescript-theme-core": "^2.0.24", from the package.json?

**Comment by bundyo** [comment]
Yes, you don't need it anymore. I'm closing this.
