### ISSUE TITLE
What's the correct setup for version 2.2.*

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#230]
I'm trying to migrate my app - using theme 2.2 and scss.

I tried to generate a sample template app (navigation /scss) and it sets up scss files differently.

The documentation for this plugin - does'nt say anything about _app and _variables files etc.

What's the correct structure of the required files and also their contents - as far as @includes are concerned.

Using this doc - I've just got 1 app.scss file and the following two includes

`@import "~@nativescript/theme/core";
@import "~@nativescript/theme/blue";
`

Thanks.

**Comment by bundyo** [comment]
There is a migration guide on a PR [here](https://github.com/NativeScript/theme/blob/52694a97d1328f08997917148f0990d208ebee1c/MIGRATION-GUIDE.md).
