### ISSUE TITLE
Calling getMode() before app start crashes (Android)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/theme#231]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:6.2
 - Android Runtime:6.2
 - iOS Runtime:
 - Plugin(s):2.2.0

**Describe the bug**
Calling Theme.getMode() before app start crashes on Android.

In ios 13 and Android 29 - will the app start up correctly based on system settings for dark mode?

What if the app is open and then the system change is made - is there a notification of change in mode?

**Comment by bundyo** [comment]
Theme API is not connected to the dark mode introduced in {N} 6.2, so it will start correctly on supported platforms regardless of importing the Theme API. If the app is open and a change to the system mode is made - {N} App should fire the [systemAppearanceChangedEvent](https://github.com/NativeScript/NativeScript/blob/release/nativescript-core/application/application-common.ts#L58)

**Comment by erjdriver** [comment]
ok - but I should be able to call getMode() before app start - right?

It's a bug.

**Comment by bundyo** [comment]
I've already marked it as one. 😉

**Comment by erjdriver** [comment]
Any idea when this will be fixed?

I would like the app to respect the current device settings for dark-mode.
