### ISSUE TITLE
Module not found tns-core-modules/ui/core/view/view-common

### ISSUE THREAD

**Issue by DevPlus31** [NativeScript/theme#235]
**Environment**

 - CLI: 6.2.2
 - Cross-platform modules: 6.2.3
 - Android Runtime: 6.2.0
 - nativescript-theme-core : 2.0.24

I am getting this error 
`ERROR in ../node_modules/nativescript-theme-core/index.js
Module not found: Error: Can't resolve 'tns-core-modules/ui/core/view/view-common' in 'C:\MobileApp\project\node_modules\nativescript-theme-core'
 @ ../node_modules/nativescript-theme-core/index.js 14:18-70
 @ ./main.js`

**To Reproduce**
Just tns debug android with configs above.

**Expected behavior**
Normal compilation.

**Comment by bundyo** [comment]
Use `@nativescript/theme` package in 6.2, `nativescript-theme-core` is not updated anymore and its last version doesn't support scoped packages.

**Comment by DevPlus31** [comment]
Thanks

**Comment by Eonfuzz** [comment]
Why is there no mention of the module name change in the documentation anywhere?

**Comment by bundyo** [comment]
The docs are not yet updated. The PR is merged, but not yet released.

https://github.com/NativeScript/docs/blob/master/docs/ui/theme.md
