### ISSUE TITLE
Getting an error when calling setMode

### ISSUE THREAD

**Issue by jannomeister** [NativeScript/theme#238]
I'm using nativescript-angular and I updated my `nativescript-theme-core` to the latest and fix the breaking changes.

But when I try to call the `Theme.setMode` I'm having a webpack issue

<img width="1186" alt="Screen Shot 2019-12-13 at 12 49 25 PM" src="https://user-images.githubusercontent.com/46916819/70770261-9aad1600-1da7-11ea-8be5-7665af2c5487.png">

**Comment by rushairer** [comment]
use "@nativescript/theme": "^2.2.1" 
replace nativescript-theme-cor

**Comment by bundyo** [comment]
Yes, `nativescript-theme-core` is the old name of the package, which is not updated anymore. The new one is `@nativescript/core`, update to get the latest changes.

Closing this issue.
