### ISSUE TITLE
Stuck in Dark Mode

### ISSUE THREAD

**Issue by baron159** [NativeScript/theme#242]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
- CLI: 6.3.0
- Cross-platform modules: 6.3.2
- Android Runtime: 6.3.1
- iOS Runtime: 6.3.0
- Plugin(s):
  - nativescript-theme-core: 2.0.24
  - @nativescript/theme: 2.2.1  <--- This Repository
  - nativescript-vue: 2.4.0
  - nativescript-vue-navigator: 0.2.0
  - nativescript-ui-sidedrawer: 8.0.0
  - @nstudio/nativescript-cardview: 1.0.0,
  - @nstudio/nativescript-checkbox: 1.0.0,
  - @nstudio/nativescript-floatingactionbutton: 1.1.0
 

**Describe the bug**

I added the theme core into my existing project. I set the mode to dark using ```Theme.setMode(Theme.Dark);``` and rebuilt the app. The app was in Dark mode. I now set it to light mode using ```Theme.setMode(Theme.Light);``` and the app remains in Dark mode. I implemented a toggle function that uses the ```Theme.toggleMode(false);``` and still the app remains in Dark mode.

**To Reproduce**

1.  Add the theme core to your project
2. Set the mode using Theme.Dark
3. Re-build the app & the app should be in dark mode
4. Set the mode using Theme.Light
5. Re-build the app
6. App still rendering in dark mode <---Issue

**Expected behavior**

When I use the Dark and Light mode or toggle the mode it should render the respective selection

**Comment by phazonoverload** [comment]
I have the same issue

**Comment by bundyo** [comment]
Sorry for the late reply, had some pressing things to do. 

I noticed something strange in your setup, can you check if this will help, since mode changing works here (with underlying light mode of the OS)?

> nativescript-theme-core: 2.0.24
> @nativescript/theme: 2.2.1 <--- This Repository

Why do you add both the old and new theme packages? @nativescript/theme is the only package needed - remove the other one.

And I have a question - you never mentioned on which OS this happens - can you clarify if on Android, iOS or both?

**Comment by baron159** [comment]
So I noticed I was using the older package as well, and when through and removed it. And the probably persists. 
I am having the issue on Android. Idk about @phazonoverload 

I had a thought. Since Android and iOS are moving towards OS level theme (Light & Dark). Could the OS be over ridding something? I use Dark mode on my device.

**Comment by baron159** [comment]
Okay, so following my last comment I decided to test my thought with the OS level Dark Theme.

As it turns out, when I turn off the OS Dark theme and start the app. It now renders in Light mode.

This seems related too issue #239 

So the OS's theming must be over-riding the app's

**Comment by bundyo** [comment]
Yep, that's what happens. The fix is now on a PR, so probably will be merged soon.

**Comment by baron159** [comment]
Awesome to hear. Is there going to be a way to allow the OS default?

**Comment by bundyo** [comment]
Yes, there are now 3 modes - Light, Dark and Auto.

**Comment by bundyo** [comment]
The @next version is now online, can you check if it works for you?
https://www.npmjs.com/package/@nativescript/theme/v/2.3.0-2020-01-13-101337-01#setting-dark-or-light-mode-from-javascript

**Comment by baron159** [comment]
Sorry for the delay....I have tried the @next version and it is working! Thank you for your effort on this.
