### ISSUE TITLE
Upgrade to V2 Breaks App--Even Backward.

### ISSUE THREAD

**Issue by EdJones** [NativeScript/theme#246]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.3
 - Cross-platform modules:
 - Android Runtime: 6.2
 - iOS Runtime: 6.2
 - Plugin(s): 2.0.24 / 1.0.6

**Describe the bug**
This probably isn't the place, but I don't know where to put it.

First, I upgraded tns to 6.3.3. Then I used Sidekick to upgrade a number of plugins, including Theme, @mdi/font, rxjs, and Babel.
At each plugin upgrade, I made a new Git commit.
At the end, when I tested on Sidekick, I got `File to import not found or unreadable: nativescript-theme-core/scss/light`

After trying all the doc-suggested fixes, I tried manually resetting package.js to use V1.4 Still no love.

So, I backed through my Git commits, trying to get back my working app.

After reverting back past all the updates, I still get `File to import not found or unreadable: nativescript-theme-core/scss/light`

I deleted the platforms folder several times, tried "Clean Build" several times, and deleted package-lock. I also did and npm install --save nativescript-theme-core@1.0.6

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by bundyo** [comment]
Theme v2 has breaking changes and indeed doesn't work out of the box with older usage. That said, maybe you should have read the [migration guide](https://github.com/NativeScript/theme/blob/master/MIGRATION-GUIDE.md).

Did you try removing node_modules too? Since you didn't mention it.
