### ISSUE TITLE
Applying the theme prevents setting TabStrip's highlightColor

### ISSUE THREAD

**Issue by vtrifonov** [NativeScript/theme#254]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.2
 - Android Runtime: 6.4.0
 - iOS Runtime: 6.4.0
**Describe the bug**

If you apply the theme the highlighColor property set on a TabStrip does not get into account.

**Expected behavior**

The highlighColor to be applied to the selected indicator.

**Sample project**
Open [the following project](https://play.nativescript.org/?template=play-tsc&id=pKAVGU&v=3). Scan it on ios/android and see the color of the Tabs selected indicator.
See the **app.css** file.

Open [the first version of the project](https://play.nativescript.org/?template=play-tsc&id=pKAVGU&v=1) with the commented default theme in **app.css**. The **highlightColor** is set to `red`, but is not applied.

**Comment by bundyo** [comment]
This is part of a bigger issue - in {N} the CSS overrides properties set locally in the component's XML.
