### ISSUE TITLE
Inconsistent library names

### ISSUE THREAD

**Issue by programista25** [NativeScript/theme#268]
In one of your articles https://nativescript.org/blog/an-early-look-at-the-new-nativescript-core-theme/ you are writing about using 
`@import "~nativescript-theme-core/index";`
but in documentation for this repo there is different naming of the theme:
`@import "~@nativescript/theme/css/core.css";`

I'm also confused which of those libraries should I use?
```
"@nativescript/theme": "2.3.3",
"nativescript-theme-core": "2.0.24",
```

So what is the right way to use it?

**Comment by bundyo** [comment]
This is mentioned in several issues and also in the readme - `@nativescript/theme` is the latest package name and the previous one is deprecated. The blog post is rather old, sorry.
