### ISSUE TITLE
Dark Mode background color always darken then defined

### ISSUE THREAD

**Issue by sivo1981** [NativeScript/theme#287]
**Environment**
√ Getting NativeScript components versions information...
√ Component nativescript has 7.0.12 version and is up to date.
√ Component @nativescript/core has 7.0.13 version and is up to date.
√ Component @nativescript/ios has 7.0.6 version and is up to date.
√ Component @nativescript/android has 7.0.1 version and is up to date.

**Describe the bug**
How to disable automatic darking of defined background colors in dark mode.

Light mode (OK):
`<Button text="BUTTON" backgroundColor="yellow" />`

![image](https://user-images.githubusercontent.com/71483000/102981840-dc6bb300-4509-11eb-84ee-25faa02c2d18.png)

Dark mode (defined color is always darken):
`<Button text="BUTTON" backgroundColor="yellow" />`

![image](https://user-images.githubusercontent.com/71483000/102981947-09b86100-450a-11eb-8c0f-a70138484b0d.png)

This issue appears only on Android.

Is there a way to override this?

**Comment by sivo1981** [comment]
Setting `<item name="android:forceDarkAllowed">false</item>` in App_Resources\Android\src\main\res\values-v29\styles.xml resolves this issue.

**Comment by Whip** [comment]
@sivo1981 The colors are indeed accurate after this change. Any unintended consequence of this?
