### ISSUE TITLE
Latest version should be tagged v2.3.4 not 2.3.4 as NPM is failing to pull it as latest

### ISSUE THREAD

**Issue by sbacon94** [NativeScript/theme#288]
The latest version should be tagged V2.3.4 and not 2.3.4 as NPM is failing to pull it.

**Comment by NathanaelA** [comment]
I can't duplicate this.   NPM  pulled v2.3.4 fine.
My package.json (from a new `tns create demo --js` says: `    "@nativescript/theme": "~2.3.0",`
The pacakge.json in the node_modules/@nativescript/theme shows this:
![image](https://user-images.githubusercontent.com/850871/103713680-95a6a000-4f82-11eb-980a-0dc540ee30aa.png)

As you can see in the package shows it pulled 2.3.4...
