### ISSUE TITLE
SideBar

### ISSUE THREAD

**Issue by TheOriginalJosh** [NativeScript/theme#29]
Getting there:
Android
<img width="283" alt="screen shot 2016-08-28 at 9 13 06 am" src="https://cloud.githubusercontent.com/assets/1486275/18034015/0c3d8cac-6d00-11e6-9a42-e5b0c2f79c93.png">

iOs
<img width="379" alt="screen shot 2016-08-28 at 9 15 44 am" src="https://cloud.githubusercontent.com/assets/1486275/18034016/0ed08b0e-6d00-11e6-88a0-161e8ca6cd8f.png">

**Comment by NathanWalker** [comment]
closing in favor of the remaining concerns documented here:
https://github.com/NativeScript/theme/issues/83
