### ISSUE TITLE
tns-core-modules limitations

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#4]
I’m going to start a list of limitations in the core modules that prevent us in some capacity from implementing the theme.

Here’s the list: https://docs.google.com/document/d/1oXph6aXz352ZH7zUJ4neh57PBtlm60IxDKJUg-xvXa8/edit.

**Comment by NathanaelA** [comment]
Per side borders

**Comment by tjvantoll** [comment]
@NathanaelA: Good one. On the list now.

**Comment by tzraikov** [comment]
Hmm, we have a highlighted pseudo-state for the button. It applies when the button is touched (pressed). I think it could help to solve issue #3

**Comment by tjvantoll** [comment]
Hey @tzraikov, I just tried out `button:pressed { ... }` and it doesn’t appear to work with {N} 2.2. Also I don’t see it listed [on the docs](https://docs.nativescript.org/ui/styling) at all.

**Comment by NathanaelA** [comment]
@tzraikov @tjvantoll - the pseudo state is `button:highlighted`   see my blog post..  ;-)

http://fluentreports.com/blog/?p=363

**Comment by tjvantoll** [comment]
@NathanaelA: Ah! Ok that makes sense. I’m not sure where I got `:pressed` from anyways because it’s not even a web thing. (Perhaps we should have used `:active`?) I need more coffee apparently.

I went ahead and checked off that item off the main list, because I _think_ that’s all we’ll need for the theme.

**Comment by toddanglin** [comment]
Definitely need to get this added to the docs. :) Very helpful piece of information.

Also agree that `:active` would be a more natural pseudo selector for web developers.

Now if only we supported [CSS Transitions](https://github.com/NativeScript/NativeScript/issues/1894) so we could smoothly animate between states. :)

**Comment by triniwiz** [comment]
Setting `selectedColor` for tabview https://github.com/NativeScript/NativeScript/issues/767#issuecomment-152502459

**Comment by triniwiz** [comment]
Also it would be nice to get `:active` for `TabView`

**Comment by triniwiz** [comment]
Input field cursor color

**Comment by triniwiz** [comment]
colorControlNormal & colorControlNormal for textfield 
![image](https://cloud.githubusercontent.com/assets/6695919/17902733/76c626e2-6936-11e6-8369-dd18f35f6c43.png)

**Comment by triniwiz** [comment]
styling searchbar icons

**Comment by tjvantoll** [comment]
Hey @triniwiz,

When you have a chance, can you create an issue for each of these blockers on the NativeScript/NativeScript repo that goes into more detail on what you need? I’d like to have each problem I list on the top be an open issue somewhere for tracking.

**Comment by tjvantoll** [comment]
Also I have box shadow on the top of this list. Have we confirmed that we definitely need box shadow? If so it would be great if someone could create that specific issue so this list is more actionable. I’m going to remove it until we can verify.

**Comment by NathanWalker** [comment]
@tjvantoll we do need box-shadow. Issue here:
https://github.com/NativeScript/NativeScript/issues/550

<img width="361" alt="screen shot 2016-08-31 at 11 24 54 am" src="https://cloud.githubusercontent.com/assets/457187/18141256/abc3ad0a-6f6d-11e6-8ff8-741319ac283d.png">

**Comment by NathanWalker** [comment]
I am not seeing `text-transform` work on iOS or Android.

**Comment by sitefinitysteve** [comment]
The Android Progress background is a tad translucent where the iOS one is the exact hex I set it to... for consistency (and user sanity) I think this needs to be adjusted if possible.

![image](https://cloud.githubusercontent.com/assets/1542376/18144560/3bc40b44-6f95-11e6-9d61-705ce9cf6bda.png)

**Comment by NathanaelA** [comment]
@NathanWalker I believe text-transform only works on a couple items, one of them is buttons.    I do know it works for sure on Buttons for sure as I am using it two projects and you can see the different on Android 5+ easily.   However, on buttons there is one state that doesn't seem to have been considered, it doesn't have a "unmodified" state.

the `None` state unfortunately then buttons then use there own defaults and on Android 6 upper case the whole word; I would love another state to be added `asis` that disables the buttons default state rendering like the other states do; but doesn't modify the text being brought in...  :grinning:

**Comment by triniwiz** [comment]
Saw this for the Input cursor color https://github.com/NativeScript/NativeScript/pull/1013

**Comment by triniwiz** [comment]
Not the best but https://github.com/NativeScript/NativeScript/issues/2656

**Comment by tjvantoll** [comment]
Both box shadow and TextField’s line color (for Android) are on the master list now. Thanks for creating those issues.

**Comment by firescript** [comment]
this isn't exactly css but I do find myself adding this often to fix up the actionbar on ios:
```
    if (page.ios) {
        navigationBar.shadowImage = new UIImage();
        navigationBar.setBackgroundImageForBarMetrics(new UIImage(), UIBarMetrics.UIBarMetricsDefault)
    }   
```  
I think it would make sense to have a property on actionbar xml like: `actionBarShadow="false"` to get rid of it.

The other thing is I cant seem to set the actionbar to transparent? `background-color:transparent;` would make sense, in combination with the shadow property on the action bar, it would give me a clean, transparent actionbar. However instead it seems to be dark grey?

If i need status bar to be translucent I can always add 
```
page.backgroundSpanUnderStatusBar = true;
navigationBar.translucent = true;
```

**Comment by sitefinitysteve** [comment]
I'm with ryan, id love to see these become core... In the shadow image case though, id say css box-shadow so we could add to the theme without requiring xml on the actionbar.

**Comment by bradmartin** [comment]
Scrap the android spec for side drawer: https://github.com/telerik/nativescript-ui-samples/issues/118#issuecomment-244366540

**Comment by sitefinitysteve** [comment]
Tabs Need:
- [ ] CSS: text-transform uppercase
- [ ] CSS: highlighted (for selected tab... selectedColor exists as XML property, but we need to sass it to $accent)

**Comment by NathanWalker** [comment]
Focus/blur pseudo selectors for forms,textfields, etc. https://github.com/NativeScript/NativeScript/issues/2181 (Added to punch list above as well)

**Comment by sitefinitysteve** [comment]
Segmented Bar:

- [ ] Border Radius
- [ ] Selected\Highlighted pseudo support

**Comment by sitefinitysteve** [comment]
- [ ] Could use border-radius: 50% support (for images)

**Comment by hshristov** [comment]
@tjvantoll I see a lot of new issues described in the comments. Could you please prioritise them so that we know what is a must and work on it for 2.4.0?

**Comment by atanasovg** [comment]
@tjvantoll We are in a process of planning the 2.4 release and the new theme is one of our top priorities. Since there are quite some bullets in the comments you will help us a lot if we can get a list with all the bullets ordered by priority - for example an updated first comment in this issue - so that we can estimate and see what can get into 2.4. We will need @myninka input here as well as the guys that contribute to the theme.

**Comment by tjvantoll** [comment]
Hey @hshristov and @atanasovg,

Ok, I moved the list to a Google Doc, because me maintaining a list of checkboxes here isn’t scaling all that well:  https://docs.google.com/document/d/1oXph6aXz352ZH7zUJ4neh57PBtlm60IxDKJUg-xvXa8/edit. The docs is public so everyone should be able to comment.

@NathanWalker @sitefinitysteve @triniwiz @TheOriginalJosh: Please help me build up this list so we can get some of these changes on the 2.4 roadmap. Leave opinions in the doc on what you think the most important issues are so engineering can prioritize.

**Comment by tjvantoll** [comment]
@hshristov @atanasovg: Is there a date you’d like to see this ready by? I’m going to be out a good chunk of next week because of Dev Day, so I’m hoping some of the others on this thread can help build up this list.
