### ISSUE TITLE
Distribution - postinstall script

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#52]
The postinstall script should do the following:

* Prompt user if they would like the raw `sass` src or just compiled `css`.
* If `y` to `sass`:
  * Copy https://github.com/NativeScript/theme/tree/master/app/scss folder to their app folder in a `scss` folder if it doesn't exist. If a folder with that name already exists, it could either prompt to override *or* we could avoid all that if we just place in a unique custom folder name of our choosing (I'm indifferent on this).
  * Copy the main 4 base theming files from here: https://github.com/NativeScript/theme/tree/master/app
    * `core.light.ios.scss`
    * `core.dark.ios.scss`
    * `core.light.android.scss`
    * `core.dark.android.scss`
    * These can be copied into their base `app` folder or can be copied to the custom folder the other files were copied too, either way.
* If `n`:
  * Copy the compiled css files of the 4 files above only to user's base `app` folder or custom folder.

Distribution to npm should compile the `scss` fresh everytime and publish `app/**/*.css` and the `app/**/*.scss` files (excluding `app.ios.scss/css` and `app.android.scss/css` since those are just for the demo). And it should ignore everything else.

In future, we may publish with a `fonts` folder and include copying those fonts to user's app `fonts` folder. Right now, we aren't including custom fonts yet, however considering that as an option in the postinstall script would be good at this point so we're prepared when we do that.

/cc @NathanaelA

**Comment by tjvantoll** [comment]
@NathanWalker: Personally I’d prefer the script to just assume CSS, and require users to opt into SASS.

This theme will be installed on every new app by default; therefore we’re going to have a lot of new users that will have no idea what’s going on, and every new question we ask them has the potential to confuse them and drive them away. Considering the `nativescript-dev-sass` plugin now allow you to import SASS files from npm modules, I’d prefer we document that path for advanced usage.

**Comment by NathanaelA** [comment]
I tend to agree with T.J. -- less questions is easier on new users.  

 But I have absolutely no issue making it ask about sass; if that is your call -- or maybe a better way would be making it auto-detect if sass is present in the package.json and then automatically installing the sass stuff in that case...   ;-)

**Comment by NathanWalker** [comment]
Completely agree @tjvantoll . Let's stay away from the questions for this first pass @NathanaelA  . Let's just do a copy of the css files 👍

**Comment by NathanWalker** [comment]
postinstall script working well.
