### ISSUE TITLE
UX review: iOS

### ISSUE THREAD

**Issue by myninka** [NativeScript/theme#66]
**ActionBar**
- [ ] 1. _Question from a designer, maybe silly_ Can the user change easily the background color with the primary accent one? And of course the foreground color if needed? May be we can predefine ActionBars with all the possible color we ship the theme with?

**Basics**
- [ ]  2. Some of the font styles requires setting the font-family, not the fon-style/font-weight property, which is something different. For example the button should have font-family: SF UI Text Medium

**Buttons**
- [x] 3. The buttons should have font-family: SF UI Text Medium
- [x] 4. border-radius: 4 of .btn-rounded-sm
- [x] 5. Can we set one huge number for border-radius of .btn-rounded-lg just to make sure whatever button height the user sets the button will have this ellipse kind-of form? Is it working that way?
- [x] 6. Something wrong happens with the pressed states. The pressed color is not the same - you can check all the colors and their pressed option in the Theme.png file in infowrap. The text color is also changing for some reason - I see this is a known issue, just putting it here for consistency. 
- [ ] 7. Also idea from the design which I cannot seem to find implemented: the full screen width without padding of the button - in the case when the user wants its button to take the whole width and stick to the edges of the screen. May be I am missing something?

**Forms** 
- [ ] 8. _Feedback wanted_ Do you think the textbox height is huge? How do you feel to set the size to 40 or 38dp especially to those textboxes with 4 borders?
- [x] 9. border-width looks like is more than 1, should be 1 (and it is - looking at &.input-border,  &.input-sides in https://github.com/NativeScript/theme/blob/5ee9ad877af90002a0407e9f1dfcc5b44184f991/app/scss/_forms.scss)
- [x] 10. Label font-weight is normal. The font of the labels above the textbox is SF UI Text Regular 12, for this inline is SF UI Text Regular 15
- [x] 11. The same question as **5** but for text boxes. 
- [x] 12. The smaller border-radius is 2
- [x] 13. The left/right margins of the four bordered textboxes should be 15 - now they seem smaller
- [ ] 14. Highlighting of the label and the border in the primary accent color when active. 
- [ ] 15. Error/info message styles support. It will be nice to give to the users if they have such feature out-of-the-box with the theme.
- [ ] 16. The same question as **7** for the textboxes.
- [ ] 17. Disabled state is missing

**Switches**
- [ ] 17. "Thumb" part of the disabled ON switch is missing

**Tabs**
- [ ] 18. https://github.com/NativeScript/theme/issues/44#issuecomment-246094648
- [ ] 19. The question from **1** is the same here for the tabs. 

**Segmented bar**
- [ ] 20. I see that at the moment it is unstyleable but to add some clarification on the design. My idea is to have 2 styles - one in the primary color and one in white and the user to be able to choose between them easily.

**ListView** I know this is work in progress so I won't go in huge level of detail here
- [ ] 21. _Question from a designer, maybe silly_ Which ListView are we styling - the core one or the NS UI one? If it is the core one do you think the same rules will apply to the NS UI one?
- [ ] 22. The top/bottom padding of the list items looks bigger than the design. I have measured it around 24. By design should be 16.
- [ ] 23. The start of the item borders are not aligned with the start of the item content - the contents are around 6pt indentation - should be 0.
- [ ] 24. My idea in the design is to have style for borders too - to be full width, to have only left margin or to have left and right margin of the screen. Is this possible?
- [ ] 25. Also Idea from the design: thumbnail to be top- center- or bottom aligned with the text.

**Side Drawer**
- [ ] 26. It is very cool but am I looking at the dark skin version? How can I take a look at the light one?
- [ ] 27. Do we have one just with the menu items, without the header?

**Comment by TheOriginalJosh** [comment]
Hi @myninka I've address some of the Button issues in https://github.com/NativeScript/theme/pull/68. I don't think I can address #5 since if the radius gets set to a number higher than a 1/4 fo the hight it will start to become pointed. I will work on #7 later

**Comment by TheOriginalJosh** [comment]
11 and 5 will work for android.

**Comment by NathanWalker** [comment]
@myninka regarding 1. actionbar - 
best way to do that would likely be to use `SASS` and modify the variables for you own use cases. However we could also define several actionbar variables like `$actionbar-blue, $actionbar-green`, etc.
