### ISSUE TITLE
Module dependencies in package.json

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/theme#69]
Is it possible that we remove `tns-core-modules`, `nativescript-telerik-ui`, and other dependencies from the theme?

The `nativescript-telerik-ui` one is especially problematic since you'd get that package even when your app doesn't use nativescript-telerik-ui. To add insult to injury, you'll also get the GIVE ME YOUR ~~SOUL~~EMAIL prompt which will likely fail your CI build :)

Of course, we can keep those packages around as devDependencies.

**Comment by TheOriginalJosh** [comment]
Can anyone think of a reason we should not we do the same for `nativescript-dom`, `nativescript-fonticon`, and `nativescript-themes`.  or are there plans for those and a setup script of sorts?

**Comment by NathanWalker** [comment]
@hdeshev @TheOriginalJosh The dependencies in this package: https://github.com/NativeScript/theme/blob/master/package.json  do not affect what is published.
The builder script creates an entirely different package to publish which has no dependencies, which I believe is best at this point until we have a `setup` script that users may call which would programmatically setup other items as mentioned here: 
https://github.com/NativeScript/theme/issues/42

This is what is used as the package template when creating the publishable build:
https://github.com/NativeScript/theme/blob/master/nativescript-theme-core.json
See this: https://github.com/NativeScript/theme#publishing
