### ISSUE TITLE
Discussion: Images

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/theme#7]
I worked up a issue with TNS #5 and while I was expounding the issues with straight NPM install with T.J.; it dawned on me a possible good solution for distributing images in the theme.   

But I think this should be a discussion...  ;-)

My Fake theme was 
```
lightWave.css
images\Name.png
images\Name@2x.png
images\Name@3x.png
images\Name@4x.png
```

I believe that distributing them in a folder using the standard iOS image naming scheme makes sense; although we could change it slightly for more clarity and consistency:
```
lightWave.css
images\Name@1x.png
images\Name@2x.png
images\Name@3x.png
images\Name@4x.png
```

The nice thing about this structure is that all four 1x, 2x, 3x, 4x actually map to equivalent android resolutions; and as such the post install can actually copy (& rename) them to the proper ios AND android resource folders.  Android will automatically downsize the 2x version for the missing hdpi/tvdpi images at runtime.   However, to support a themer's who really really wants to create separate android specific versions; I'm thinking we should also support...

```
images\Name@tvdpi.png
images\Name@hdpi.png
...
images\Name@xxxdpi.png
```

Thoughts?

**Comment by tjvantoll** [comment]
@NathanaelA Sorry, just saw this. There’s also the common use case of wanting to use different images on iOS and Android. Because of that you might need to mirror the `App_Resources` structure, which would probably make implementing a hook a bit easier.

```
theme.css
images\
    Android\
        drawable-hdpi
            Name.png
    iOS\
        Name@1x.png
        Name@2x.png
        Name@3x.png
```

**Comment by NathanaelA** [comment]
Well, I think my case covered that.  ;-)

```
images\Name@1x.png
images\Name@2x.png
images\Name@3x.png
images\Name@hdpi.png
```

This would automatically 
Use Name@hdpi for image@1x on Android; but use @2x and @3x for xdpi and xxdpi on Android.   ;-)    My preference is simplicity; I personally hate navigating down to a image/android/drawable-hdpi; why not just drop all the images in the /images folder and be done with it. 

  But I do think we should come up with an consensuses of which people prefer.   I personally prefer a flatter directory structure...

**Comment by tjvantoll** [comment]
@NathanaelA Ah gotcha, I missed that detail the first time.

I’m definitely in favor of avoiding the various dpi folders for Android, as those are indeed a massive pain. I only suggested `Android` and `iOS` folders for consistency with `App_Resources`, but I’d prefer dropping those folders in favor of your naming convention.

**Comment by NathanWalker** [comment]
Closing in favor of remaining issue doc.
