### ISSUE TITLE
Colors for Headers Question

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/theme#73]
Should colors be set for `h1,h2,h3...`? https://github.com/NativeScript/theme/blob/master/app/scss/_labels.scss#L17

My vote is to not set a color for the `h1,h2,h3...` classes. I had a label in a test project, using an icon font in a stack-layout and wanted color white but used the utility `h3` for some sizing on the label and of course it has color set.  

Header tags make no assumption of color on the web, it's just size so.... curious to hear others thoughts and why it's coded for the `$primary` and `$secondary` colors.

**Comment by NathanWalker** [comment]
We will move to how bootstrap is handling this with a variable:
https://github.com/twbs/bootstrap/blob/295c93846c154fb461f85b30e663102f7e171104/scss/_type.scss

**Comment by NathanWalker** [comment]
@bradmartin colors are no longer used with h1, h2, etc. 👍  Instead a similar pattern as bootstrap above is used.
This allows the dark skin to provide a color (to inverse/contrast the background). The light/default has no color falling back on defaults.
