### ISSUE TITLE
Documentation updates needed for v1

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#81]
- [x] Document the ActionBar class names.
- [x] Show modal usage of ActionBar class names.
- [x] Show how to build disabled textboxes.
- [x] Explain how to use the theme’s SASS code.
  - [x] Show how to override color variables.
- [x] Add screenshots of the two color schemes.
- [x] Document page class as required to use the dark skin (it will control background color) https://github.com/NativeScript/theme/issues/93
- [x] Talk about `.btn-active`, ScrollViews, and iOS.
- [x] Change the uninstallation documentation to account for Nathanael’s new uninstaller.
- [x] All the new skins https://github.com/NativeScript/theme/pull/108#issuecomment-260399466
- [x] Document status bar usage

**Comment by burkeholland** [comment]
Just a note that in the current state, you can require in the SASS files, but you have to specify the platform in the path

`@import "nativescript-theme-core/core.dark.ios";`

Without specifying the entire path, the import will fail during the SASS build step.

**Comment by tjvantoll** [comment]
@burkeholland Thanks for logging that. We’re addressing the SASS workflow with https://github.com/NativeScript/docs/pull/586/files. Let me know if you have any concerns.

**Comment by tjvantoll** [comment]
Should be good to go with https://github.com/NativeScript/docs/pull/587.
