### ISSUE TITLE
Switch: disabled ON switch on iOS missing the “Thumb”

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#82]
See the third switch down:

![screen shot 2016-10-03 at 4 53 03 pm](https://cloud.githubusercontent.com/assets/544280/19053694/ddfcc8c0-8989-11e6-9de0-39071dd3e9d1.png)

Essentially when you disable an ON switch, it looks kind of odd on iOS. Look into why that is and whether we can do anything about it.

**Comment by NathanWalker** [comment]
Fixed on master now 👍 
![screen shot 2016-10-03 at 1 55 16 pm](https://cloud.githubusercontent.com/assets/457187/19053760/18cbe27e-8971-11e6-875c-6f8da0fb3eae.png)
