### ISSUE TITLE
SideDrawer - light/dark version + menu items without header

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#83]
@TheOriginalJosh if you don't mind taking this one sometime this week. Maybe we'll add back a `SideDrawer` item in the pages which can change out or nav to different pages of altered `SideDrawer` setups to help answer @myninka concerns:
- Am I looking at the dark skin version? How can I take a look at the light one?
- Do we have one just with the menu items, without the header?

**Comment by NathanWalker** [comment]
Regarding Android specifically:

* The font of the menu items should be Roboto Medium 14.

**Comment by TheOriginalJosh** [comment]
https://github.com/NativeScript/theme/pulls includes side-drawer light theme, and setting the font to Roboto Medium 14.

we don't have an example without the header however removing the sidedrawer header element in the sidedrawer renders fine. 
![screenshot_20161017-224620](https://cloud.githubusercontent.com/assets/1486275/19462562/b8688e22-94bb-11e6-9738-08de1fd1dfbb.png)
![screenshot_20161017-224636](https://cloud.githubusercontent.com/assets/1486275/19462561/b865802e-94bb-11e6-8008-5a18b8e9bd6c.png)
