### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#84]
So I wrote some [documentation on how to uninstall the theme](http://docs.nativescript.org/ui/theme#uninstalling), and I found that I had to tell people to manually remove the theme files from the CSS folder. That’s icky. Does npm let you provide an uninstall hook that we could use to kill those files?

**Comment by NathanaelA** [comment]
Yes, we can create a uninstall script that does a de-install of the files...   Is that in scope for v1?

**Comment by tjvantoll** [comment]
> Yes, we can create a uninstall script that does a de-install of the files... Is that in scope for v1?

Awesome! I don’t think the script is essential for v1, but if it’s not too complex it’d be great to have it in there.

**Comment by NathanWalker** [comment]
Uninstall is in 0.1.5
