### ISSUE TITLE
ActionBar auxillary classes to style with different background colors, etc.

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#85]

**Comment by NathanWalker** [comment]
@myninka Please provide hex value colors for background and accent when possible...

**Comment by myninka** [comment]
**Default light and dark in the theme**
Light or dark background with accent color any of these:
`#8130ff, #3d5afe, #30bcff, #aee406, #00caab, #006968, #5c687c, #ffea00, #f57c00, #ff1744, #795548`

**Color styles from auxiliary classes**
Background/Accent
1.  `#30bcff`/`#ffea00`
2.  `#00caab`/`#aee406`
3.  `#f57c00`/`#795548`
4.  `#ff1744`/`#ffea00`
5.  `#aee406`/`#006968`
6.  `#795548`/`#aee406`
7.  `#00caab`/`#aee406`
8.  `#8130ff`/`#30bcff`
9.  `#3d5afe`/`#30bcff`
10. `#5c687c`/`#aee406`
11. `#ffea00`/`#5c687c`

**Comment by bradmartin** [comment]
Might be worthwhile to mention the Android primaryDark color being used in the specs also and mention the native code to apply it programmatically or instructions to set via colors.xml.

``` typescript
import { isAndroid, device } from "platform";
import { Color } from "color";

if (isAndroid && device.sdkVersion >= "21") {
      let window = android.startActivity.getWindow();
      window.setStatusBarColor(new Color("#d32f2f").android);
}
```

**Comment by NathanWalker** [comment]
@myninka I'm having second thoughts on how we should distribute these.
I assume these become **themes** themselves. For instance, let's say we call #1 `sky`, and if you were to use `sky`, I assume all styles across the theme should become that skin, so the accent on `sky` (our potential name for #1) would be `#ffea00` (`lemon` color) on every class that used the `$accent` color?

If that is correct, then I think we *may* want to publish these as separate theme packages.
The alternate route is to generate a total of 11 extra css files to compile these different themes that user's could use. If they are using `SASS` then it would be easier since we could have import order documented on how to apply a certain set. But regarding just `css` usage, we would need to distribute 11 more css files for these, potentially double (22) since we would need `light` in addition to `dark` compilations with these color sets.
Just thinking about best strategy here, any thoughts?

/cc @NathanaelA @bradmartin @TheOriginalJosh
