### ISSUE TITLE
Thorough review of dark color scheme

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#86]
Make sure the dark color scheme looks ok, and colors are changed appropriate for all class names the theme has.

**Comment by tjvantoll** [comment]
@NathanWalker: The dark color scheme doesn’t seem to work as part of the demo app. If you go to the “Themes” page and tap “Apply Dark” nothing seems to happen. Any idea what’s up?

**Comment by NathanWalker** [comment]
@tjvantoll skin themes are now fixed on latest master with the above commit 👍
