### ISSUE TITLE
Update the default app templates

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/theme#87]
The following app templates should be updated to use the new theme.
- [x] https://github.com/NativeScript/template-hello-world
- [ ] https://github.com/NativeScript/template-hello-world-ts
- [ ] https://github.com/NativeScript/template-hello-world-ng

**Comment by tjvantoll** [comment]
Ping @myninka. 

Below are screenshots that we’re going to tentatively use for the new default app templates. Basically we added an ActionBar, a TabView, and a bit of text that we hope points users in the right direction. I wanted to check to see if you had any feedback about what we have so far before we move forward.

cc @NathanWalker 

Here’s the main, “Home” tab on iOS:

![screen shot 2016-10-14 at 2 48 16 pm](https://cloud.githubusercontent.com/assets/544280/19399065/a0478398-921d-11e6-9122-3d922ab5e0a4.png)

Here’s the second, “Theme” tab on iOS:

![screen shot 2016-10-14 at 2 51 48 pm](https://cloud.githubusercontent.com/assets/544280/19399094/c32d21b0-921d-11e6-80b8-697fca5dfe67.png)

And here’s the main tab on Android:

![screen shot 2016-10-14 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/544280/19399063/9ee5fc46-921d-11e6-987e-76c9046f551a.png)

**Comment by myninka** [comment]
Hey @tjvantoll 
I think it would be better if we remove tabbar and the button and leave only the text with the ActionBar. The tabbar could be a part from a different app template, as well as the side drawer menu. Let's leave it simple for now. 
What do you think?

**Comment by NathanWalker** [comment]
@myninka @tjvantoll I agree. We can update https://www.npmjs.com/package/tns-template-tab-navigation to have the tabs, etc. 👍

**Comment by tjvantoll** [comment]
@NathanWalker: Seems like we have one final update to make to the main template. Want to make the final changes? I can merge them and then we can move on to the next two templates.

**Comment by NathanWalker** [comment]
@tjvantoll @myninka the base template is now updated per suggestions.
https://github.com/NativeScript/template-hello-world/pull/50

![simulator screen shot oct 19 2016 1 25 26 pm](https://cloud.githubusercontent.com/assets/457187/19536146/97fe33ae-95ff-11e6-9762-b86a72acc8a2.png)

**Comment by TheOriginalJosh** [comment]
@NathanWalker I really like that! super clean

**Comment by tjvantoll** [comment]
Merged the first template change 🎉

**Comment by NathanWalker** [comment]
@tjvantoll hooray! Do you want me to apply the same setup to `-ts` and `-ng` templates?

**Comment by tjvantoll** [comment]
@NathanWalker There were some concerns about the changes from engineering (basically the same concerns we voiced in Slack about the template not feeling native enough), so let’s hold off for now. I’m going to try to get a meeting scheduled so we can figure out the best way to move forward.
