### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/theme#9]

**Comment by NathanWalker** [comment]
@bradmartin there is now a dedicated page in the demo app to build these out:
https://github.com/NativeScript/theme/blob/master/app/pages/sliders.xml

**Comment by TheOriginalJosh** [comment]
https://github.com/NativeScript/theme/pull/34

**Comment by bradmartin** [comment]
Sorry for being MIA - house moving totally screwed me out. I'll try to do something to help out if needed coming up on the conf date.

**Comment by TheOriginalJosh** [comment]
No worries man, moving is a giant pita, completely understand. I just knocked this out tonight cause it seemed like some low hanging fruit. There is still plenty work to be done :)

**Comment by NathanWalker** [comment]
basic sliders are complete. The remaining custom thumb icon control is yet to be supported.
