### ISSUE TITLE
Comment in theme files incorrectly state theme semantic version 

### ISSUE THREAD

**Issue by mikebranstein** [NativeScript/theme#91]
The comment line in the CSS and SCSS files current states NativeScript Theme x0.1.0, where the package version is currently 0.1.3. 

This could be confusing. Ideally, this would be something that your release build addresses.

**Comment by NathanWalker** [comment]
@mikebranstein good one 👍  Fixed now with `0.1.4` published now.

**Comment by mikebranstein** [comment]
Thanks! 🌮
